apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: ingress-envoy
spec:
  controller: networking.k8s.io/ingress-envoy-controller
  parameters:
    apiGroup: k8s.example.com
    kind: IngressParameters
    name: external-lb